// tb_sobel_core.sv
//
// Directed testbench for sobel_core. Every expected value here was
// computed BY HAND (see chat explanation), not generated by any
// reference model. This is intentional: at this stage we are
// verifying our own understanding of the math as much as the RTL.

module tb_sobel_core;

    logic [7:0] p00, p01, p02;
    logic [7:0] p10, p11, p12;
    logic [7:0] p20, p21, p22;
    logic [7:0] magnitude;

    int errors = 0;
    int tests  = 0;

    initial begin
        $dumpfile("sobel_wave.vcd");
        $dumpvars(0, tb_sobel_core);
    end

    // Instantiate the DUT (Device Under Test)
    sobel_core dut (
        .p00(p00), .p01(p01), .p02(p02),
        .p10(p10), .p11(p11), .p12(p12),
        .p20(p20), .p21(p21), .p22(p22),
        .magnitude_o(magnitude)
    );

    // Reusable check task: drive inputs, wait for combinational
    // settling, compare against a hand-computed expected value.
    task automatic check_case(
        string      name,
        logic [7:0] i_p00, i_p01, i_p02,
        logic [7:0] i_p10, i_p11, i_p12,
        logic [7:0] i_p20, i_p21, i_p22,
        logic [7:0] expected
    );
        p00 = i_p00; p01 = i_p01; p02 = i_p02;
        p10 = i_p10; p11 = i_p11; p12 = i_p12;
        p20 = i_p20; p21 = i_p21; p22 = i_p22;

        #1; // allow combinational logic to settle before sampling

        tests++;
        if (magnitude !== expected) begin
            errors++;
            $display("FAIL [%0s]: expected %0d, got %0d", name, expected, magnitude);
        end else begin
            $display("PASS [%0s]: magnitude = %0d", name, magnitude);
        end
    endtask

    initial begin
        // Test 1: all-zero window -> no gradient at all
        check_case("all_zero",
            8'd0, 8'd0, 8'd0,
            8'd0, 8'd0, 8'd0,
            8'd0, 8'd0, 8'd0,
            8'd0);

        // Test 2: uniform bright window -> no gradient (flat region)
        check_case("all_255_uniform",
            8'd255, 8'd255, 8'd255,
            8'd255, 8'd255, 8'd255,
            8'd255, 8'd255, 8'd255,
            8'd0);

        // Test 3: sharp vertical edge (left col=0, right col=255)
        // Hand calc: Gx = 255 + 2*255 + 255 = 1020, Gy = 0
        // sum = 1020 -> saturates to 255
        check_case("vertical_edge_saturate",
            8'd0, 8'd128, 8'd255,
            8'd0, 8'd128, 8'd255,
            8'd0, 8'd128, 8'd255,
            8'd255);

        // Test 4: sharp horizontal edge (top row=0, bottom row=255)
        // Hand calc: Gy = 255 + 2*255 + 255 = 1020, Gx = 0
        // sum = 1020 -> saturates to 255
        check_case("horizontal_edge_saturate",
            8'd0,   8'd0,   8'd0,
            8'd128, 8'd128, 8'd128,
            8'd255, 8'd255, 8'd255,
            8'd255);

        // Test 5: small positive Gx, Gy forced to zero by symmetry
        // (row0 == row2 for columns 0/2, and p01==p21)
        // Hand calc: Gx = (110-100) + 2*(70-70) + (110-100) = 20, Gy = 0
        check_case("small_positive_gx",
            8'd100, 8'd80, 8'd110,
            8'd70,  8'd0,  8'd70,
            8'd100, 8'd80, 8'd110,
            8'd20);

        // Test 6: moderate negative Gx, Gy forced to zero by symmetry
        // Hand calc: Gx = (150-200) + 2*(50-50) + (150-200) = -100, Gy = 0
        // abs(Gx) = 100, sum = 100 -> no saturation
        check_case("moderate_negative_gx",
            8'd200, 8'd90, 8'd150,
            8'd50,  8'd0,  8'd50,
            8'd200, 8'd90, 8'd150,
            8'd100);

        $display("---------------------------------------------");
        $display("TESTS RUN: %0d   FAILURES: %0d", tests, errors);
        if (errors == 0)
            $display("RESULT: ALL TESTS PASSED");
        else
            $display("RESULT: FAILURES DETECTED");
        $display("---------------------------------------------");

        $finish;
    end

    // Optional waveform dump for debugging in a viewer like GTKWave
    initial begin
        $dumpfile("tb_sobel_core.vcd");
        $dumpvars(0, tb_sobel_core);
    end

endmodule